// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMItumAALYUVxzCUWShpizpKqPfxY0lg',
    appId: '1:863732232076:web:936d5857cb7a74be71f0a9',
    messagingSenderId: '863732232076',
    projectId: 'flutterexam-5c5fe',
    authDomain: 'flutterexam-5c5fe.firebaseapp.com',
    storageBucket: 'flutterexam-5c5fe.appspot.com',
    measurementId: 'G-WG9WXCCGRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNdOX256y7kqiNbowOnGz9uz-ykxcsK0',
    appId: '1:863732232076:android:a56f11aa71f8336771f0a9',
    messagingSenderId: '863732232076',
    projectId: 'flutterexam-5c5fe',
    storageBucket: 'flutterexam-5c5fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkiSuVtIUdwxm3OzEawRV8Lvw961kMTgI',
    appId: '1:863732232076:ios:8d6cbe30a09e83a971f0a9',
    messagingSenderId: '863732232076',
    projectId: 'flutterexam-5c5fe',
    storageBucket: 'flutterexam-5c5fe.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkiSuVtIUdwxm3OzEawRV8Lvw961kMTgI',
    appId: '1:863732232076:ios:8d6cbe30a09e83a971f0a9',
    messagingSenderId: '863732232076',
    projectId: 'flutterexam-5c5fe',
    storageBucket: 'flutterexam-5c5fe.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIMItumAALYUVxzCUWShpizpKqPfxY0lg',
    appId: '1:863732232076:web:7e06bf7b5ebb5d6271f0a9',
    messagingSenderId: '863732232076',
    projectId: 'flutterexam-5c5fe',
    authDomain: 'flutterexam-5c5fe.firebaseapp.com',
    storageBucket: 'flutterexam-5c5fe.appspot.com',
    measurementId: 'G-Z0HZE5GE20',
  );
}
